name: CI - Build and Push Docker Compose Images

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: docker-compose.yml
      IMAGE_TAG: latest

    steps:
      # 🧩 STEP 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 🧩 STEP 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🧩 STEP 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🧩 STEP 4: Build all images with Docker Compose
      - name: Build all images
        run: |
          echo "🔨 Building Docker images using docker compose..."
          docker compose -f $COMPOSE_FILE build --no-cache

      # 🧩 STEP 5: Tag and push images to DockerHub
        # Each service must match the service name in docker-compose.yml
      - name: Tag and push images to DockerHub
        run: |
          echo "🚀 Tagging and pushing images to DockerHub..."

          # Define image mappings: service_name=image_name_in_compose
          declare -A images=(
            [authservice]="${{ secrets.DOCKERHUB_USERNAME }}/authservice"
            [userservice]="${{ secrets.DOCKERHUB_USERNAME }}/userservice"
            [loggerservice]="${{ secrets.DOCKERHUB_USERNAME }}/loggerservice"
            [nginx]="${{ secrets.DOCKERHUB_USERNAME }}/nginx-gateway"
          )

          # Tag and push each image
          for service in "${!images[@]}"; do
            echo "Pushing image for $service..."
            docker tag "$service" "${images[$service]}:$IMAGE_TAG"
            docker push "${images[$service]}:$IMAGE_TAG"
          done

          echo "✅ All Docker images successfully pushed to DockerHub."

      # 🧩 STEP 6: Upload docker-compose.yml as artifact (optional)
      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml
          retention-days: 5
