name: CI - Build and Push Docker Compose Images

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: docker-compose.yml
      IMAGE_TAG: latest

    steps:
      # 🧩 STEP 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 🧩 STEP 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🧩 STEP 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🧩 STEP 4: Build service images using Docker Compose
      - name: Build all images
        run: |
          echo "🔨 Building Docker images using docker-compose..."
          docker compose -f $COMPOSE_FILE build --no-cache

      # 🧩 STEP 5: Tag and push images to DockerHub
      - name: Push Docker images to DockerHub
        run: |
          echo "🚀 Pushing built images to DockerHub..."
          docker images
      
          # Match docker-compose naming pattern
          services=(authservice userservice loggerservice)
      
          for service in "${services[@]}"; do
            local_image="microserviceapp-$service"
            remote_image="${{ secrets.DOCKERHUB_USERNAME }}/$service:$IMAGE_TAG"
      
            echo "Tagging and pushing $local_image -> $remote_image"
            docker tag "$local_image:latest" "$remote_image"
            docker push "$remote_image"
          done
      
          echo "✅ All images pushed successfully."

      # 🧩 STEP 6: Upload docker-compose.yml as artifact (optional)
      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml
          retention-days: 5
