name: CI - Build and Push Docker Images

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_FILE: docker-compose.yml
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🔹 Build and push AuthService
      - name: Build and push AuthService image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/authservice:$IMAGE_TAG -f backend/src/AuthService/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/authservice:$IMAGE_TAG

      # 🔹 Build and push UserService
      - name: Build and push UserService image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/userservice:$IMAGE_TAG -f backend/src/UserService/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/userservice:$IMAGE_TAG

      # 🔹 Build and push LoggerService
      - name: Build and push LoggerService image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/loggerservice:$IMAGE_TAG -f backend/src/LoggerService/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loggerservice:$IMAGE_TAG

      # 🔹 Build and push Nginx (optional, if using custom config)
      - name: Build and push Nginx image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-gateway:$IMAGE_TAG -f nginx/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-gateway:$IMAGE_TAG

      - name: Verify pushed images
        run: |
          echo "✅ Successfully pushed images:"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/authservice:$IMAGE_TAG"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/userservice:$IMAGE_TAG"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/loggerservice:$IMAGE_TAG"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/nginx-gateway:$IMAGE_TAG"
